os: linux
dist: bionic
language: c

services:
  - docker

script:
  - make --no-builtin-rules build

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make --no-builtin-rules publish
    - curl -X POST "https://hooks.microbadger.com/images/virtualstaticvoid/ldhdns/$MICROBADGE_TOKEN"
  on:
    branch: master
