---
services:

  # docker-compose logs --follow ldhdns
  ldhdns:
    image: ldhdns:latest

    container_name: ldhdns
    environment:
      LDHDNS_CONTAINER_NAME: ldhdns

    network_mode: host
    security_opt:
    - "apparmor=unconfined"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"

  # docker-compose logs --follow altldhdns
  altldhdns:
    image: ldhdns:latest

    container_name: altldhdns
    environment:
      LDHDNS_CONTAINER_NAME: altldhdns
      LDHDNS_DOMAIN_SUFFIX: alt.dns

    network_mode: host
    security_opt:
    - "apparmor=unconfined"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"

  # curl -v http://web.ldh.dns
  # curl -v http://web.alt.dns
  web:
    image: nginx:latest
    networks:
      - frontend
    labels:
      "dns.ldh/subdomain": "web"

  # curl -v http://api.ldh.dns
  # curl -v http://api.alt.dns
  api:
    image: nginx:latest
    networks:
      - frontend
      - backend
    labels:
      "dns.ldh/subdomain": "api"

  # psql -h pgsql.ldh.dns -U postgres
  # psql -h pgsql.alt.dns -U postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "p@ssw0rd"
    networks:
      - backend
    labels:
      "dns.ldh/subdomain": "pgsql"

networks:
  frontend:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24
      - subnet: 2001:3000:3000::/64

  backend:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/24
      - subnet: 2001:3100:3100::/64
