---

x-ldhdns: &ldhdns
  image: ghcr.io/virtualstaticvoid/ldhdns:$VERSION
  build:
    args:
      - VERSION
      - S6_VERSION
  network_mode: host
  security_opt:
  - "apparmor=unconfined"
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"

services:

  default-controller:
    container_name: ldhdns
    <<: *ldhdns

  alternative-controller:
    container_name: altldhdns
    <<: *ldhdns
    environment:
      LDHDNS_NETWORK_ID: altldhdns
      LDHDNS_DOMAIN_SUFFIX: alt.dns
      LDHDNS_SUBDOMAIN_LABEL: alt.ldh/subdomain
      LDHDNS_CONTAINER_NAME: altldhdns

  web:
    image: nginx:1.22.0-alpine
    networks:
      - frontend
    labels:
      "dns.ldh/subdomain": "web"
      "alt.ldh/subdomain": "web2"

  api:
    image: nginx:1.22.0-alpine
    networks:
      - frontend
      - backend
    labels:
      "dns.ldh/subdomain": "api"
      "alt.ldh/subdomain": "api2"

  postgres:
    image: postgres:14.3-bullseye
    environment:
      POSTGRES_PASSWORD: "p@ssw0rd"
    networks:
      - backend
    labels:
      "dns.ldh/subdomain": "pgsql"
      "alt.ldh/subdomain": "pgsql2"

  test:
    build:
      dockerfile: Dockerfile.test
    network_mode: host
    environment:
      PGPASSWORD: "p@ssw0rd"
    profiles:
      - test

networks:
  frontend:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24
      - subnet: 2001:3000:3000::/64

  backend:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/24
      - subnet: 2001:3100:3100::/64
