#!/usr/bin/with-contenv sh
echo >&2 "Starting dnsmasq service"
exec dnsmasq --keep-in-foreground \
             --conf-file=/etc/ldhdns/dnsmasq/dnsmasq.conf \
             --hostsdir="${DNSMASQ_HOSTSDIR}" \
             --pid-file="${DNSMASQ_PIDFILE}" \
             --local-ttl=${DNSMASQ_LOCAL_TTL} \
             --log-facility=-
